pipeline:
  name: server_provisioning
  identifier: server_provisioning
  projectIdentifier: CiscoLive
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: baelengit
        repoName: BRKCLD-2015
        build: <+input>
  stages:
    - stage:
        name: Intersight Provisioning
        identifier: Intersight
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            key: cache-{{ checksum "requirements.txt" }}
            paths:
              - /root/.cache
          execution:
            steps:
              - step:
                  type: Run
                  identifier: dependencies
                  name: Dependencies
                  spec:
                    shell: Sh
                    command: |-
                      python -m pip install --upgrade pip
                      pip install -r requirements.txt
                    envVariables:
                      PIP_CACHE_DIR: /root/.cache
              - step:
                  type: Run
                  identifier: insertApiKey
                  name: Insert API key
                  spec:
                    shell: Sh
                    command: echo $SECRET > key.txt
                    envVariables:
                      SECRET: <+secrets.getValue("intersight_key")>
              - step:
                  type: Run
                  name: Execute Intersight Workflow
                  identifier: intersight_wf
                  spec:
                    shell: Sh
                    command: python ico_wf_execute_by_name.py --api-key-legacy <+variable.INTERSIGHT_API_KEY_ID> --api-key-file key.txt
                    envVariables:
                      PIP_CACHE_DIR: /root/.cache
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
