pipeline:
  name: server_provisioning
  identifier: server_provisioning
  projectIdentifier: CiscoLive
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: baelengit
        repoName: BRKCLD-2015
        build: <+input>
  stages:
    - stage:
        name: Intersight Provisioning
        identifier: Intersight
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            key: cache-{{ checksum "requirements.txt" }}
            paths:
              - /root/.cache
          execution:
            steps:
              - step:
                  type: Run
                  identifier: dependencies
                  name: Dependencies
                  spec:
                    shell: Sh
                    command: |-
                      python -m pip install --upgrade pip
                      pip install -r requirements.txt
                    envVariables:
                      PIP_CACHE_DIR: /root/.cache
              - step:
                  type: Run
                  identifier: insertApiKey
                  name: Insert API key
                  spec:
                    shell: Sh
                    command: |-
                      echo  <+secrets.getValue("intersight_key_rtp")> | base64 -d > key.txt
                      echo  "<+secrets.getValue("intersight_key_rtp")> | base64 -d"
                    envVariables:
                      PIP_CACHE_DIR: /root/.cache
              - step:
                  type: Run
                  name: Execute Intersight Workflow
                  identifier: intersight_wf
                  spec:
                    shell: Sh
                    command: python ico_wf_execute_by_name.py --api-key-legacy --api-key-file key.txt
                    envVariables:
                      PIP_CACHE_DIR: /root/.cache
                      INTERSIGHT_API_KEY_ID: 636d24f77564612d3375a70e/63dbc8737564612d304e2ba9/63ed31497564612d3004c16e
                      INTERSIGHT_ORG: 636d24fc6972652d3071677c
                      INTERSIGHT_WF_NAME: Create NTP Policy
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          sharedPaths:
            - /root/.cache
